hash-format = "sha256"

[[files]]
file = "README.md"
hash = "23b73b88f3722cfed7cf26e0fe787e7cb873b1d9f50175ed25bd84f865b036a9"

[[files]]
file = "config/bcc-common.toml"
hash = "96c2fe003420fc545711acb0afb190401329f11f7908affdaa8c9410fb662c7e"

[[files]]
file = "config/fancymenu/config.txt"
hash = "23bc7bc49ede621380844ab2683d6da0120b5ef4166cfc0b08a9ed74e65d3e70"

[[files]]
file = "config/fancymenu/minecraftwindow/icons/icon16x16.png"
hash = "e9ffab03ce5ffc826c37ee3e1b7216fc3f37545464b8d70fcad85dd907a392ee"

[[files]]
file = "config/fancymenu/minecraftwindow/icons/icon32x32.png"
hash = "7a04c2d6f6ec75a6af8ef5834dfb9e64746651546069f046925ad81e96390e07"

[[files]]
file = "config/fancymenu/resources/background.png"
hash = "3e8235d16dd967bb3de5a6c10344aa181b8d3aea687ff7719c9d9b015fa70a06"

[[files]]
file = "config/fancymenu/resources/logo.png"
hash = "bd13011ba5df43fe2ce224a1f931e3a5033fe0dc29c9659d3238df0c6df8a4c3"

[[files]]
file = "config/fancymenu/resources/pack_version.txt"
hash = "05c64cb6a9476411f5c1be2445cb7e163b575262cf76c1c116348335d4f9686e"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "72c817cd5696a46324adcfbbd61cabe296ff941629991d212df790ccab6d1112"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "0e845067aa4b98088aac8a92d8429fb627dfe0fdd127d725ebb6166d85efad43"
metafile = true

[[files]]
file = "mods/simply-swords.pw.toml"
hash = "557e893a9a60af60b34d2a2a04feb2082c1d02285a2b476e56309d4fec7bda60"
metafile = true

[[files]]
file = "shaderpacks/ComplementaryReimagined_r1.4.zip"
hash = "592c12605d03c345e15698d6020a892c865f56b3bcb117bcc9e41358f7df6584"

[[files]]
file = "shaderpacks/ComplementaryShaders_v4.6.zip"
hash = "aa7f493d7d95e3b6785beba19cd2a5d5df579e6f66dbc56e3de7c4cfdc0aea74"

[[files]]
file = "shaderpacks/Sildur's+Vibrant+Shaders+v1.50+Extreme-VL.zip"
hash = "42978cfc9d4ae2048d33ac0b9d1632b6a408d573f600b0e516197ecb21d4f608"
